/**
 * Tests for url field in Service type
 * Verifies type compatibility and fixture support
 */
import { describe, it, expect } from 'vitest'
import { createService, createHttpService } from '@/test/fixtures'
import type { Service } from '@/types'

describe('Service url field', () => {
  it('should accept url as optional string', () => {
    const service: Service = createService({
      name: 'test-service',
      url: 'https://custom.example.com',
    })

    expect(service.azure?.url).toBe('https://custom.example.com')
  })

  it('should work without url field', () => {
    const service: Service = createService({
      name: 'test-service',
    })

    expect(service.azure?.url).toBeUndefined()
  })

  it('should support url in HTTP services', () => {
    const service = createHttpService({
      name: 'web',
      url: 'https://myapp.ngrok.io',
    })

    // Local URL is auto-generated by factory
    expect(service.local?.url).toBeTruthy()
    // Custom URL is stored in azure.url
    expect(service.azure?.url).toBe('https://myapp.ngrok.io')
  })

  it('should preserve url in service with Azure configuration', () => {
    const service: Service = createService({
      name: 'api',
      url: 'https://api.example.com',
    })

    // When url is provided, it's stored in azure.url
    expect(service.azure?.url).toBe('https://api.example.com')
  })

  it('should type-check url as string or undefined', () => {
    const service = createService({ name: 'test' })
    
    // TypeScript should accept these patterns for azure.url
    const url1: string | undefined = service.azure?.url
    const url2 = service.azure?.url ?? 'default-url'
    const hasurl = !!service.azure?.url
    
    expect(url1).toBeUndefined()
    expect(url2).toBe('default-url')
    expect(hasurl).toBe(false)
  })
})
