version: 2

project_name: azd-app-cli

builds:
  - id: azd-app
    main: ./src/cmd/app
    binary: azd-app
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -trimpath

archives:
  - id: azd-app-cli
    name_template: >-
      azd-app-cli-{{ .Os }}-{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - extension.yaml
      - src/internal/dashboard/dist/**/*

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

release:
  github:
    owner: jongio
    name: azd-app
  name_template: "v{{.Version}}"
  draft: false
  prerelease: auto

# Don't publish anywhere - we use azd x publish for that  
publishers:
  - name: skip
    cmd: echo "Skipping publish - using azd x publish"
