package azure

import (
	"context"
	"fmt"
	"sort"
	"strings"
)

// BicepTemplateResponse represents the API response for the Bicep template generator.
type BicepTemplateResponse struct {
	Template     string               `json:"template"`
	Services     []string             `json:"services"`
	Instructions BicepInstructions    `json:"instructions"`
	Parameters   []BicepParameterInfo `json:"parameters"`
}

// BicepInstructions provides guidance on how to integrate the template.
type BicepInstructions struct {
	Summary string   `json:"summary"`
	Steps   []string `json:"steps"`
}

// BicepParameterInfo describes a required parameter for the template.
type BicepParameterInfo struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Example     string `json:"example"`
}

// BicepGenerator generates Bicep templates for diagnostic settings.
type BicepGenerator struct {
	discovery *ResourceDiscovery
}

// NewBicepGenerator creates a new Bicep template generator.
func NewBicepGenerator(discovery *ResourceDiscovery) *BicepGenerator {
	return &BicepGenerator{
		discovery: discovery,
	}
}

// GenerateTemplate generates a consolidated Bicep template for all detected services.
func (g *BicepGenerator) GenerateTemplate(ctx context.Context) (*BicepTemplateResponse, error) {
	// Discover resources
	result, err := g.discovery.Discover(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to discover resources: %w", err)
	}

	if len(result.Resources) == 0 {
		return nil, fmt.Errorf("no Azure resources found in environment")
	}

	// Collect service types
	serviceTypes := make(map[ResourceType]bool)
	serviceNames := make([]string, 0, len(result.Resources))

	for serviceName, resource := range result.Resources {
		serviceTypes[resource.ResourceType] = true
		serviceNames = append(serviceNames, serviceName)
	}

	// Sort service names for consistent output
	sort.Strings(serviceNames)

	// Generate Bicep template
	template := g.generateBicepModule(serviceTypes)

	// Build instructions
	instructions := g.buildInstructions(serviceTypes)

	// Build parameter info
	parameters := g.buildParameters()

	return &BicepTemplateResponse{
		Template:     template,
		Services:     serviceNames,
		Instructions: instructions,
		Parameters:   parameters,
	}, nil
}

// generateBicepModule creates a Bicep module with diagnostic settings for all service types.
func (g *BicepGenerator) generateBicepModule(serviceTypes map[ResourceType]bool) string {
	var sb strings.Builder

	// Header comment
	sb.WriteString("// Diagnostic Settings Module\n")
	sb.WriteString("// This module configures diagnostic settings for Azure resources to send logs to Log Analytics.\n")
	sb.WriteString("// Generated by azd app\n\n")

	// Parameters section
	sb.WriteString("// Parameters\n")
	sb.WriteString("@description('Resource ID of the Log Analytics Workspace')\n")
	sb.WriteString("param logAnalyticsWorkspaceId string\n\n")

	// Add resource-specific parameters and diagnostic settings
	if serviceTypes[ResourceTypeContainerApp] {
		sb.WriteString(g.generateContainerAppDiagnostics())
	}

	if serviceTypes[ResourceTypeAppService] {
		sb.WriteString(g.generateAppServiceDiagnostics())
	}

	if serviceTypes[ResourceTypeFunction] {
		sb.WriteString(g.generateFunctionDiagnostics())
	}

	return sb.String()
}

// generateContainerAppDiagnostics generates diagnostic settings for Container Apps.
func (g *BicepGenerator) generateContainerAppDiagnostics() string {
	return `@description('Name of the Container App')
param containerAppName string

// Reference existing Container App
resource containerApp 'Microsoft.App/containerApps@2023-05-01' existing = {
  name: containerAppName
}

// Configure diagnostic settings for Container App
resource containerAppDiagnostics 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: 'logs-to-analytics'
  scope: containerApp
  properties: {
    workspaceId: logAnalyticsWorkspaceId
    logs: [
      {
        category: 'ContainerAppConsoleLogs'
        enabled: true
        retentionPolicy: {
          enabled: true
          days: 30
        }
      }
      {
        category: 'ContainerAppSystemLogs'
        enabled: true
        retentionPolicy: {
          enabled: true
          days: 30
        }
      }
    ]
    metrics: [
      {
        category: 'AllMetrics'
        enabled: true
        retentionPolicy: {
          enabled: true
          days: 30
        }
      }
    ]
  }
}

`
}

// generateAppServiceDiagnostics generates diagnostic settings for App Services.
func (g *BicepGenerator) generateAppServiceDiagnostics() string {
	return `@description('Name of the App Service')
param appServiceName string

// Reference existing App Service
resource appService 'Microsoft.Web/sites@2022-09-01' existing = {
  name: appServiceName
}

// Configure diagnostic settings for App Service
resource appServiceDiagnostics 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: 'logs-to-analytics'
  scope: appService
  properties: {
    workspaceId: logAnalyticsWorkspaceId
    logs: [
      {
        category: 'AppServiceHTTPLogs'
        enabled: true
        retentionPolicy: {
          enabled: true
          days: 30
        }
      }
      {
        category: 'AppServiceConsoleLogs'
        enabled: true
        retentionPolicy: {
          enabled: true
          days: 30
        }
      }
      {
        category: 'AppServiceAppLogs'
        enabled: true
        retentionPolicy: {
          enabled: true
          days: 30
        }
      }
      {
        category: 'AppServicePlatformLogs'
        enabled: true
        retentionPolicy: {
          enabled: true
          days: 30
        }
      }
    ]
    metrics: [
      {
        category: 'AllMetrics'
        enabled: true
        retentionPolicy: {
          enabled: true
          days: 30
        }
      }
    ]
  }
}

`
}

// generateFunctionDiagnostics generates diagnostic settings for Azure Functions.
func (g *BicepGenerator) generateFunctionDiagnostics() string {
	return `@description('Name of the Function App')
param functionAppName string

// Reference existing Function App
resource functionApp 'Microsoft.Web/sites@2022-09-01' existing = {
  name: functionAppName
}

// Configure diagnostic settings for Function App
resource functionAppDiagnostics 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: 'logs-to-analytics'
  scope: functionApp
  properties: {
    workspaceId: logAnalyticsWorkspaceId
    logs: [
      {
        category: 'FunctionAppLogs'
        enabled: true
        retentionPolicy: {
          enabled: true
          days: 30
        }
      }
    ]
    metrics: [
      {
        category: 'AllMetrics'
        enabled: true
        retentionPolicy: {
          enabled: true
          days: 30
        }
      }
    ]
  }
}

`
}

// buildInstructions creates integration instructions for the Bicep template.
func (g *BicepGenerator) buildInstructions(serviceTypes map[ResourceType]bool) BicepInstructions {
	steps := []string{
		"Save this template as infra/modules/diagnostic-settings.bicep in your project",
		"Ensure your main.bicep has a Log Analytics workspace resource or parameter",
		"Add module reference in main.bicep after your service resources",
		"Pass the required parameters (workspace ID and resource names)",
		"Run 'azd up' to deploy the diagnostic settings",
	}

	return BicepInstructions{
		Summary: "Add this module to your Bicep infrastructure to enable diagnostic settings",
		Steps:   steps,
	}
}

// buildParameters creates parameter documentation.
func (g *BicepGenerator) buildParameters() []BicepParameterInfo {
	return []BicepParameterInfo{
		{
			Name:        "logAnalyticsWorkspaceId",
			Description: "Resource ID of the Log Analytics Workspace where logs will be sent",
			Example:     "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-rg/providers/Microsoft.OperationalInsights/workspaces/my-workspace",
		},
	}
}
